# Generated by Django 5.1.1 on 2024-10-04 02:36

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_balance_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID'),
        ),
    ]
