# Generated by Django 5.1.1 on 2024-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_product_options_alter_productsale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local da Venda'),
        ),
    ]
