# Generated by Django 5.1.1 on 2024-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_sale_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Recarga'), (1, 'Compra')], verbose_name='Tipo'),
        ),
    ]
