# Generated by Django 5.1.1 on 2024-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_saleproduct_sale_products_delete_productsale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="events",
            field=models.ManyToManyField(
                related_name="products", to="event.event", verbose_name="Eventos"
            ),
        ),
    ]
