# Generated by Django 5.1.1 on 2024-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_product_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="event.event",
                verbose_name="Eventos",
            ),
        ),
    ]
