# Generated by Django 5.1.1 on 2024-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Empresa')),
                ('ico_url', models.URLField(max_length=255, verbose_name='Ícone URL')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de criação')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
