# Generated by Django 5.1.1 on 2024-09-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'Histórico de Login'},
        ),
    ]
