# Generated by Django 5.1.1 on 2024-10-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_managers'),
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
    ]
