# Generated by Django 5.1.1 on 2024-11-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_managers_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(max_length=11, verbose_name="CPF"),
        ),
    ]
