# Generated by Django 5.1.1 on 2024-11-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_managers_alter_customuser_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="CPF"
            ),
        ),
    ]
